language: node_js

node_js:
- 0.1

env:
 global:
 - secure: "dii9HtHz9eVDmiqEwszsYDsK7xhWmt2XcuTSNdspvd/EAMQRWQ4TjgY8gfZ1XXWDxIbcN4zOyBRrhBqeOEacT17XR17tFY+Psg23z0LgUBrsFiBDInV1ToSLnFq1rfQx/2QJLQQjcF2jZRMQGY2wA//+PSaJ22bWrDu0wjOVnWU="
 - GH_REF: github.com/narqo/bem-game-go.git
 - ISTANBUL_COVERAGE: yes

branches:
 only:
 - master

install:
- npm install
- bower-npm-install

after_success:
- npm install coveralls
- ./node_modules/.bin/istanbul report lcovonly
- cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && echo "Coverage data was sent to coveralls!"
- [ "${TRAVIS_PULL_REQUEST}" == "false" ] && npm run deploy || "false"

